FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npx prisma generate
# RUN npx prisma db push


EXPOSE 3001

CMD [ "npm", "run", "start:prod" ]
