version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=
      - STEAM_API_KEY=
      - CLIENT_URL=
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
